# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import avatar.avatar_service_pb2 as avatar__service__pb2


class AvatarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetAvatar = channel.stream_unary(
                '/avatar_service.AvatarService/SetAvatar',
                request_serializer=avatar__service__pb2.SetAvatarRequest.SerializeToString,
                response_deserializer=avatar__service__pb2.SetAvatarResponse.FromString,
                )


class AvatarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetAvatar(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvatarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetAvatar': grpc.stream_unary_rpc_method_handler(
                    servicer.SetAvatar,
                    request_deserializer=avatar__service__pb2.SetAvatarRequest.FromString,
                    response_serializer=avatar__service__pb2.SetAvatarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avatar_service.AvatarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AvatarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetAvatar(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/avatar_service.AvatarService/SetAvatar',
            avatar__service__pb2.SetAvatarRequest.SerializeToString,
            avatar__service__pb2.SetAvatarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
